コード簡略化+機能改善
junsaba/route-map pull request #1
Opened 2021-07-17 12:24 UTC by Poteto143

題名通りです。
# 変更内容
- コードを簡略化し一行当たりの文字数を少なくした
- 読み込み時にすぐ路線図が表示されるようにした

2021-07-17 13:34 UTC, Takkun053 requested changes
[Deleted] (ミスです)

2021-07-17 13:35 UTC, Takkun053 requested changes
回答と修正をお願いします。

2021-07-17 13:35 UTC, Takkun053 commented on js/main.js
> +    init()
セミコロンを付けましょう！
L17とL54も

2021-07-17 13:35 UTC, Takkun053 commented on js/main.js
> +                if (Number(d3) > 0) {
この部分で何をしているかを教えてください。
僕は、もしポイントデータが最後でないなら次の座標まで線を引くってことをやろうとしていました。

2021-07-17 13:49 UTC, Poteto143 commented on js/main.js
> +                if (Number(d3) > 0) {
「もしポイントデータが最後でないなら次の座標まで線を引く」を、
「もし１つ前のポイントデータがあるならそれと結ぶ」に変えました。
見た目上の変化は無いと思います

2021-07-17 13:51 UTC, Poteto143 commented on js/main.js
> +    init()
修正しました。

2021-07-17 14:13 UTC, Takkun053 commented on js/main.js
> +    init()
17行目もお願いします...

2021-07-17 14:58 UTC, Takkun053 commented on js/main.js
> +                if (Number(d3) > 0) {
これだと、最後が表示されない気がするのですが...

2021-07-17 16:27 UTC, Poteto143 commented on js/main.js
> +                if (Number(d3) > 0) {
すみません、気づきませんでした()
修正しました

2021-07-18 00:26 UTC, Takkun053 commented on js/main.js
> +                if (Number(d3) > 0) {
```py
if (Number(d3) > 0) {
    Coord = routeData[d3]["coord"];
    ctx.lineTo(map_x + Coord [0], map_y + Coord[1]);
};
```
か
```py
if (Number(d3) < routeData.length) {
    nextCoord = routeData[Number(d3) + 1]["coord"];
    ctx.lineTo(map_x + nextCoord[0], map_y + nextCoord[1]);
};
```
にしないと最後が表示されない気が...

2021-07-18 01:09 UTC, Poteto143 commented on js/main.js
> +                if (Number(d3) > 0) {
僕の環境では最後まで表示されたので、ダウンロードして試してみてください

2021-07-18 02:55 UTC, Takkun053 commented on js/main.js
> +                if (Number(d3) > 0) {
確かにそれでできそうですね。

2021-07-18 02:57 UTC, Takkun053 requested changes
気づくの遅くなってしまいごめんなさい。
もう一か所お願いします！

2021-07-18 02:57 UTC, Takkun053 commented on js/main.js
> +}
ここもセミコロンがないです...

2021-07-18 04:00 UTC, Poteto143 commented on js/main.js
> +}
今度こそ修正しました...()

2021-07-18 04:12 UTC, Takkun053 approved these changes

2021-07-18 04:13 UTC, merged